[package]
name = "fitless"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"] }
crossterm = "0.27.0"
fit-rust = "0.1.8"
fitparser = "0.7.0"
pager = "0.16.1"
tabled = "0.18.0"
